### PR TITLE
Build for Linux RISC-V 64

### PR DESCRIPTION
**Pull request by Glavo**

### CODE REVIEW

**Comment by Glavo** [comment]
I cannot access the s3, so how should I test it?

**Comment by Glavo** [comment]
I resolved the conflict.

Since ubuntu 18.04 does not support RISC-V 64, I updated the container to ubuntu 20.04. 

It is worth noting that the general support for ubuntu 18.04 will end next month, so I believe it is reasonable to update to 20.04.

**Comment by Glavo** [comment]
I have updated this PR and now only use ubuntu 20.04 for building RISC-V 64 library.

**Comment by Glavo** [comment]
@Spasi I have updated this PR, can you take a look? If this PR is ok, I will update other PRs with reference to this PR.

**Comment by Spasi** [comment]
Hey @Glavo,

Thanks, I've merged this manually, works great.

For testing, you can download the RISC-V binaries from here: https://www.lwjgl.org/browse/nightly/linux/riscv64

**Comment by Glavo** [comment]
@Spasi 

That's great. I have updated these three PRs. Can you take a look at them?

https://github.com/LWJGL-CI/freetype/pull/2
https://github.com/LWJGL-CI/harfbuzz/pull/1
https://github.com/LWJGL-CI/jemalloc/pull/5

**Pull request closed without merging**
